// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1UDEEnv92l7_BAg6MSEXwMI2Y9tRw2fU',
    appId: '1:339844752134:web:358a3ee634fd87032fb487',
    messagingSenderId: '339844752134',
    projectId: 'couplesns-aeb74',
    authDomain: 'couplesns-aeb74.firebaseapp.com',
    storageBucket: 'couplesns-aeb74.appspot.com',
    measurementId: 'G-ZVJBRKX1M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR50ON6ItKoK7cbTm-yGHk_OLDTkqvyJs',
    appId: '1:339844752134:android:ea139812435ee5722fb487',
    messagingSenderId: '339844752134',
    projectId: 'couplesns-aeb74',
    storageBucket: 'couplesns-aeb74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBohmMTtxyUOS5wayt78tv5qAzbiockGEI',
    appId: '1:339844752134:ios:fffad11fc4edf5712fb487',
    messagingSenderId: '339844752134',
    projectId: 'couplesns-aeb74',
    storageBucket: 'couplesns-aeb74.appspot.com',
    iosBundleId: 'com.example.coupleSns',
  );
}
